"""
Equivalent to src/config/defaultIgnore.ts in repomix, but with inverted
logic: repomix starts from "everything is candidate text" and EXCLUDES
node_modules, .git, binaries, etc. Here we start from "a sample folder may
contain everything" (cover images, license PDFs, .DS_Store, synth presets...)
and only INCLUDE recognizable audio files.

System/VCS directories are still excluded just like in repomix.
"""

DEFAULT_AUDIO_EXTENSIONS: list[str] = [
    ".wav", ".wave",
    ".aif", ".aiff",
    ".flac",
    ".mp3",
    ".ogg",
    ".m4a",
]

# Directories we should never traverse, regardless of audio content
# (system metadata, version control, DAW caches).
DEFAULT_IGNORE_DIRS: list[str] = [
    ".git", ".svn",
    "__MACOSX", ".DS_Store",
    "Ableton Project Info",  # metadata folder generated by Ableton
    ".cache",
]

# Ignore control filenames the tool should honor, in the same spirit as
# IGNORE_CONTROL_FILE_NAMES in repomix fileSearch.ts.
IGNORE_CONTROL_FILE_NAMES: set[str] = {".gitignore", ".samplesignore"}
